# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-toml
    -   id: check-added-large-files
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.287
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: alembic/
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
        exclude: alembic/
-   repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.325
    hooks:
    -   id: pyright
