[database]
dialect = "postgresql"
api = "asyncpg"
host = "127.0.0.1"
port = 5432
user = "postgres"
name = "sc2sentry"

[auth]
jwt_lifetime_seconds = 3600

[minio]
endpoint = "localhost:9000"
access_key = "minioadmin"
secure = false
buckets = ["sc2sentry"]
