"""empty message

Revision ID: f6122e2b89c0
Revises:
Create Date: 2023-08-08 14:28:56.167597

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "f6122e2b89c0"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
